/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 SP1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "IN_1_aliases.h"
#include "IN_1.h"
#include "IN_2_aliases.h"
#include "IN_2.h"
#include "SB_aliases.h"
#include "SB.h"
#include "Clock_1.h"
#include "PWM_motor.h"
#include "SDA_aliases.h"
#include "SDA.h"
#include "SCL_aliases.h"
#include "SCL.h"
#include "I2C.h"
#include "I2C_PVT.h"
#include "Pin_2_aliases.h"
#include "Pin_2.h"
#include "ADC_SAR_Seq.h"
#include "in_A_aliases.h"
#include "in_A.h"
#include "in_B_aliases.h"
#include "in_B.h"
#include "QuadDec_1.h"
#include "Clock_3.h"
#include "LED_aliases.h"
#include "LED.h"
#include "isr_flag.h"
#include "Clock_2.h"
#include "UART_1.h"
#include "in_button_aliases.h"
#include "in_button.h"
#include "IN_H_aliases.h"
#include "IN_H.h"
#include "ADC_SAR_Seq_IRQ.h"
#include "ADC_SAR_Seq_theACLK.h"
#include "ADC_SAR_Seq_Bypass_aliases.h"
#include "ADC_SAR_Seq_Bypass.h"
#include "QuadDec_1_Cnt16.h"
#include "UART_1_IntClock.h"
#include "core_cm3_psoc5.h"
#include "core_cm3.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"

/*[]*/

